### PR TITLE
Handle Jest v27

### PR DESCRIPTION
**Pull request by dcavanagh**
[This Change](https://github.com/facebook/jest/pull/10926) in jest changed the structure of the config object that jest calls process with.

### CODE REVIEW

**Comment by yannbf** [comment]
Much needed change, thanks @dcavanagh! I'm running into an issue in my codebase of which this change fixed perfectly!

**Comment by nielsvanmidden** [comment]
😍

**Comment by hiddewie** [comment]
I verified that this patch works with Jest 27. Thanks!

Any indication when this can be merged and released?

**Comment by punkfest** [comment]
hi @scitech could you please take a look when you have some time? 🙏

**Comment by rlamana** [comment]
+1

**Comment by scitech** [comment]
Sorry for the delay everybody, merge and published now - let me know if you have any issues.

**Comment by yannbf** [comment]
> Sorry for the delay everybody, merge and published now - let me know if you have any issues.

No worries, thank you so much for taking the time to review and merge! Happy holidays!

**Pull request merged**
