### PR TITLE
<rootDir> support in helpers and partials configured paths

### PR DESCRIPTION
**Pull request by spiroid**
When <rootDir> is specified in helpers or partials paths, it will reference jest rootDir.
Which is, quoting the [official documentation](https://jest-bot.github.io/jest/docs/configuration.html#rootdir-string), 

> Default: The root of the directory containing the package.json or the pwd if no package.json is found

### CODE REVIEW

**Comment by jeffcarey** [comment]
Any chance this could be merged? It will be useful for a project I am working on.

**Comment by spiroid** [comment]
@scitech : is this project still active / maintained ? 
if not would you mind if we publish a forked version respecting license ?

Or maybe do you recommend switching to another lib ?

**Comment by scitech** [comment]
Thanks for the contribution and sorry for the delay!

**Comment by spiroid** [comment]
Thx for the merge and the release of the new versions :+1: :)

**Pull request merged**
